### PR TITLE
Fixed not recognising synthetic enum constructor parameters. 

### LINKED ISSUE #1: Incorrect handling of enum constructors
Scribe doesn't handle enum constructors properly, which can be seen both when mapping them and in the fact that the hints don't show up. 

This seems to be due to it not taking the synthetic `name` and `ordinal` parameters into account when generating the descriptor (and arg indices), as demonstrated by the below comparison: 

`ModelBlockRenderer$AdjacencyInfo`, mapped in Enigma:

```
    METHOD <init> (Ljava/lang/String;I[Lnet/minecraft/core/Direction;FZ[Lnet/minecraft/client/renderer/block/ModelBlockRenderer$SizeInfo;[Lnet/minecraft/client/renderer/block/ModelBlockRenderer$SizeInfo;[Lnet/minecraft/client/renderer/block/ModelBlockRenderer$SizeInfo;[Lnet/minecraft/client/renderer/block/ModelBlockRenderer$SizeInfo;)V
        ARG 3 corners
        ARG 4 brightness
        ...
```

`ModelBlockRenderer$AdjacencyInfo`, mapped in Scribe:

```
    METHOD <init> ([Lnet/minecraft/core/Direction;FZ[Lnet/minecraft/client/renderer/block/ModelBlockRenderer$SizeInfo;[Lnet/minecraft/client/renderer/block/ModelBlockRenderer$SizeInfo;[Lnet/minecraft/client/renderer/block/ModelBlockRenderer$SizeInfo;[Lnet/minecraft/client/renderer/block/ModelBlockRenderer$SizeInfo;)V
        ARG 1 corners
        ARG 2 brightness
        ...
```

**Scribe Version**: 0.1.4

### PR DESCRIPTION
**Pull request by Harleyoc1**
This PR fixes #1. This issue is explained in detail there with example. 

The fix simply adds the synthetic parameters to the descriptor and handles the offset indices accordingly. 

I have tested enum constructor hints and mapping parameter and Javadoc; all seems to be working with the fix.

### CODE REVIEW

File: src/main/kotlin/org/parchmentmc/scribe/util/desc-index-utils.kt [hunk 1]
```diff
@@ -62,4 +64,15 @@ private fun <T> PsiMethod.iterateJvmIndices(successFun: (Int, Byte) -> T?): T? {
...
+
+fun PsiMethod.getParameterIndexOffset(): Int {
+    return when {
+        this.isEnumConstructor() -> 2
+        else -> 0
+    }
+}
+
+fun PsiMethod.isEnumConstructor(): Boolean {
+    return this.isConstructor && this.findContainingClass()?.isEnum == true
```
Comment (SizableShrimp) [inline src/main/kotlin/org/parchmentmc/scribe/util/desc-index-utils.kt]: Please move both of these functions to use expression bodies

File: src/main/kotlin/org/parchmentmc/scribe/util/bytecode-utils.kt [hunk 2]
```diff
@@ -10,13 +10,7 @@
...
 package org.parchmentmc.scribe.util
 
-import com.intellij.psi.PsiArrayType
-import com.intellij.psi.PsiClass
-import com.intellij.psi.PsiClassType
-import com.intellij.psi.PsiField
-import com.intellij.psi.PsiMethod
-import com.intellij.psi.PsiPrimitiveType
-import com.intellij.psi.PsiType
+import com.intellij.psi.*
```
Comment (SizableShrimp) [inline src/main/kotlin/org/parchmentmc/scribe/util/bytecode-utils.kt]: Can you please move this back to all explicit single line imports?

File: src/main/kotlin/org/parchmentmc/scribe/util/desc-index-utils.kt [hunk 3]
```diff
@@ -30,12 +30,14 @@ import com.intellij.psi.PsiParameter
...
-        val thisIndex = containingMethod.parameterList.getParameterIndex(this)
+        val thisIndex = containingMethod.getParameterIndexOffset() + containingMethod.parameterList.getParameterIndex(this)
         return containingMethod.iterateJvmIndices { curIndex, curJvmIndex -> if (curIndex == thisIndex) curJvmIndex else null } ?: -1
     }
 
 fun PsiMethod.getParameterByJvmIndex(jvmIndex: Byte): PsiParameter? {
-    return iterateJvmIndices { curIndex, curJvmIndex -> if (curJvmIndex == jvmIndex) this.parameterList.getParameter(curIndex) else null }
+    return iterateJvmIndices { curIndex, curJvmIndex -> if (curJvmIndex == jvmIndex) {
+        this.parameterList.getParameter(curIndex - this.getParameterIndexOffset())
+    } else null }
```
Comment (SizableShrimp) [inline src/main/kotlin/org/parchmentmc/scribe/util/desc-index-utils.kt]: Formatting looks a little weird here. Since you added a new line to the closure, I would recommend inserting a newline after `->` and `else null`.

**Review by SizableShrimp — CHANGES_REQUESTED** [review]
Looks fine, mainly just some stylation changes that need addressing.

**Review by SizableShrimp — APPROVED** [review]
